server:
  port: 8080
spring:
  application:
    name: consumer
  redis:
    host: 49.232.46.23
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://mmall-eureka:8000/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: false