server:
  port: 8080
spring:
  application:
    name: consumer
  redis:
    host: 49.232.46.23
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
      #defaultZone: http://mmall-eureka:8000/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: false
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 30000