server:
  port: 9000
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
#      defaultZone: http://mmall-eureka:8000/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    user:
      path: /mmall-user/**
      serviceId: user
      strip-prefix: false
    product:
      path: /mmall-product/**
      serviceId: product
      strip-prefix: false
  sensitive-headers:
logging:
ribbon:
  ReadTimeout: 10000
  SocketTimeout: 30000
#  file: /logs/mmall.log